language: node_js

node_js:
  - "10"

sudo: false

branches:
   only:
   - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

before_script : "yarn test -- -u"

script: 
  - yarn lint
  - yarn test
  - yarn build:docs

after_script: 
  - yarn ci
  - cd .out
  - git init
  - git add .
  - git commit -m 'docs:deploy'
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
  - echo "√ publish success 🥒"

env:
  global:
    - GH_REF: github.com:cuke-ui/cuke-ui.git